import numpy as np
import os

import src.exocross as exocross
import src.dace as dace
import src.cross as cross
import src.utils as utils

def list_files(source:str, formula:str):
    match source:
        case "dace":
            return dace.list_files(formula)
        case "exocross":
            return exocross.list_files(formula)
        case _:
            raise Exception("Invalid source '%s'"% source)

# List the p,t values across all BIN files (f) in the directory
def list_all_ptf(source:str, formula:str, allow_itp:bool=True):
    files = list_files(source, formula)

    all_p = []
    all_t = []
    all_f = []
    for f in files:
        if ("Itp" in f) and (not allow_itp):
            continue
        x = cross.xsec("", source, f)
        x.parse_name()
        all_p.append(x.p)
        all_t.append(x.t)
        all_f.append(f)
    return all_p, all_t, all_f

def map_ptf(source:str, formula:str, p_targets:list=[], t_targets:list=[], allow_itp:bool=True):
    """Map p,t points covered by DACE bin files within a given directory.

    The p,t arrays will be sorted in ascending order, pressure first. 
    They do not need to have the same length, but must be 1D.
    Also returns the file paths, for them to be read fully later.

    Parameters
    ----------
    source : str
        Source of the data (e.g. "dace", "exocross")
    formula : str
        Formula of the volatile (e.g. "H2O")
    p_targets : list
        Target pressure values [bar]
    t_targets : list
        Target temperature values [K]
    allow_itp : bool
        Use bin files which were generated by interpolation?

    Returns
    -------
    np.ndarray
        pressures [bar]
    np.ndarray 
        temperatures [K]
    list 
        file paths which map to these p,t values
    """

    print("Mapping p,t points")
    print(f"    searching for {formula} in {source} data")

    # Get all points
    all_p, all_t, all_f = list_all_ptf(source, formula, allow_itp=allow_itp)
    all_n = len(all_f)
    print("    found %d files"%all_n)
    
    # Check limits
    want_n = len(p_targets) * len(t_targets)
    if want_n == 0:
        want_n = all_n
    print("    want %d files"%want_n)
    if want_n >= 2000:
        raise Exception("SOCRATES does not support more than 2000 PT points")

    # Unique P,T values
    unique_p = np.unique(all_p)
    unique_t = np.unique(all_t)

    if len(unique_p) * len(unique_t) != all_n:
        raise Exception("Files are not unique or the p,t grid is not rectilinear")

    # Find best temperatures
    print("    finding best temperatures")
    selected_t = []
    if (len(t_targets) >= len(unique_t)) or (len(t_targets) == 0):
        selected_t = unique_t[:]
    else:
        use_t = []
        search_t = list(unique_t[:])
        for t in t_targets:
            i = utils.get_closest_idx(t, search_t)
            selected_t.append(search_t[i])
            search_t.pop(i)

    # Find best pressures
    print("    finding best pressures")
    selected_p = []
    if (len(p_targets) >= len(unique_p)) or (len(p_targets) == 0):
        selected_p = unique_p[:]
    else:
        use_p = []
        search_p = list(unique_p[:])
        for p in p_targets:
            i = utils.get_closest_idx(np.log10(p), np.log10(search_p))
            selected_p.append(search_p[i])
            search_p.pop(i)
    
    # Flatten p,t points (ensure ascending order)
    use_t = []
    use_p = []
    for p in sorted(selected_p):
        for t in sorted(selected_t):
            use_t.append(t)
            use_p.append(p)

    use_t = np.array(use_t, dtype=float)
    use_p = np.array(use_p, dtype=float)
    use_n = len(use_p)

    # Map to files
    print("    mapping to files")
    atol = 1.0e-5
    use_n = len(use_p)
    modprint = int(use_n * 0.1)
    
    print("     %: ", end='')
    use_f = []
    for j in range(use_n):
        if (j+1)%modprint == 0:
            print("%d " %( (j+1)/use_n *100.0), end='', flush=True)

        for i in range(all_n):
            p = all_p[i]
            t = all_t[i]
            if np.isclose(use_p[j], p, atol=atol) and np.isclose(use_t[j], t, atol=atol):
                use_f.append(all_f[i])
                break 
    print(" ")
    use_f = np.array(use_f, dtype=str)

    # Check if things don't line up
    if (len(use_p) != len(use_t)):
        raise Exception("Mapping failed (p vs t), (%d vs %d)"%(len(use_p), len(use_t)))
    if (len(use_p) != len(use_f)):
        raise Exception("Mapping failed (p/t vs f) , (%d vs %d)"%(len(use_p), len(use_f)))
    
    # Get total size on disk (to warn user)
    size = 0.0
    for f in use_f:
        size += os.path.getsize(f)
    size *= 1.0e-9
    
    # Result
    print("    %d files mapped, totalling %g GB" % (use_n, size))
    print("    done\n")
    return use_p, use_t, use_f